### ISSUE TITLE
Permission to extract passwordless variation to gem?

### ISSUE THREAD

**Issue by tcannonfodder** [CiTroNaK/webauthn-with-devise#1]
Hey there!

With the move towards passkeys (through the FIDO Alliance, Apple's OS updates, Windows Hello, etc.); I think it would be extremely useful for the larger Ruby community to have a devise extension that can be used for passwordless authentication. Do I have permission to extract the relevant code from the passwordless branch into a gem for the devise extension?

https://github.com/CiTroNaK/webauthn-with-devise/tree/3-passwordless

**Comment by CiTroNaK** [comment]
Hi @tcannonfodder, sure. I am looking forward to it. 

Please, share the repo. I would like to help if I will find some free time.

Thanks!

**Comment by tcannonfodder** [comment]
The repo URL is here: https://github.com/devise-passkeys/devise-passkeys

**Comment by tcannonfodder** [comment]
After some more investigation & thought, I actually opened up a discussion about passkeys support within devise itself: https://github.com/heartcombo/devise/issues/5527 🤞🤞🤞

**Comment by tcannonfodder** [comment]
Moving into a larger effort to support passkeys inside devise itself
